### PR TITLE
Fixes race condition when stopping service in the goroutine

### LINKED ISSUE #7: Race condition when stop service
**Describe the bug**

Basically, when restarting the Service when other goroutines try to send requests a race condition occurs.

**To Reproduce**

1. Start the service
2. Open a goroutine to use the service instance
3. Stop the instance
4. Start again

**Expected behavior**

None race condition should happen when restarting a Service. Ideally the New factory of the sync.RWMutex should be set once for the instance (not on every start).

**Screenshots**

image

### PR DESCRIPTION
**Pull request by edumarcal**
### :bug: Bugs

* Adds test to detect race condition.
* Fixes race condition.

---

Fix: #7

### CODE REVIEW

File: service.go [hunk 1]
```diff
@@ -50,7 +51,8 @@ func (*CredentialsFromStruct) IsExpired() bool {
 
 // SQSService is the service which manages a service queue on the AWS.
 type SQSService struct {
-	serviceState
+	sync.RWMutex
```
Comment (felipemfp) [inline service.go]: Use an unexported attribute otherwise we will be able to lock and unlock at will from other packages.

```suggestion
	m sync.RWMutex
```

File: service.go [hunk 2]
```diff
@@ -134,26 +139,40 @@ func (service *SQSService) Start() error {
 		if err != nil {
 			return err
 		}
-	}
 
-	service.setRunning(true)
+		service.started = true
```
Comment (felipemfp) [inline service.go]: We could reduce this logic into one variable (`awsSQS`). Instead of setting it at line 114:

```suggestion
		service.aswSQS = awsSQS
```

Then the running method will looks like:

```go
func (service *SQSService) isRunning() bool {
	service.RLock()
	defer service.RUnlock()
	return service.awsSQS != nil
}
```

**Review by felipemfp — CHANGES_REQUESTED** [review]

File: service.go (hunk 2 above)
Comment (edumarcal) [reply service.go]: I also agree with this approach.

**Review by felipemfp — APPROVED** [review]
LGTM :tada::+1:

**Review by Jeconias — APPROVED** [review]
